name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - jupyterlab=2.2.8
  - matplotlib=3.2.2
  - numpy=1.18.5
  - pandas=1.0.5
  - python=3.7.6
  - xarray=0.15.1
  - netcdf4=1.5.3
  - dask=2.19.0 
  - zarr=2.8.3
  - s3fs=0.5.1
  - fsspec=0.8.0 
  - hvplot=0.7.3
