name: tutorialenv
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy=0.17.0
  - jupyterlab=2.2.8
  - matplotlib=3.2.2
  - numpy=1.18,5
  - pandas=1.0.5
  - python=3.7.6
  - xarray=0.15.1
  - netcdf4=1.5.3